version: '3.8'




services:
  client-backend:
    image: app/activism
    container_name: cl_bk
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:6101/activismandcharity
    ports:
      - "8181:8181"
    depends_on:
      - service-db 

  service-db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: ["postgres", "-c","port=6101"]
    ports:
      - "6101:6101"
    volumes:
      - ./infrastructure/db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    